### ISSUE TITLE
关于task.h中的await_transform和co_await如何执行

### ISSUE THREAD

**Issue by BestUO** [netcan/asyncio#11]
co_await expr会被转化为
```auto&& value = <expr>;
auto&& awaitable = **get_awaitable**(promise, static_cast<decltype(value)>(value));
auto&& awaiter = get_awaiter(static_cast<decltype(awaitable)>(awaitable));
```

而get_awaitable由下面伪代码构成
```template<typename P, typename T>
decltype(auto) **get_awaitable**(P& promise, T&& expr)
{
  if constexpr (has_any_await_transform_member_v<P>)
    return promise.await_transform(static_cast<T&&>(expr));
  else
    return static_cast<T&&>(expr);
}
```
参考task_test.cpp例子，struct Task不应该是一个awaitable对象，想问一下task.h中的await_transform是如何工作的。
调试代码，先运行await_transform再运行co_await，没弄明白参数是怎么传递的，能否做个简单提示
不胜感激

**Comment by netcan** [comment]
以`co_await task`为例，由于`Task`类的`Promies`定义了`await_transform`函数，因此会调用
```
auto task_awaiter = p. await_transform(task);
```

因为我都`await_transform`只是简单地透传一下`task`，所以
```
auto task_awaiter = task;
```
接下来就是调用`task`对象的`operator co_await`操作符拿到真正的`awaiter`，编译器会展开`awaiter`里的`await_ready/await_suspend/await_resume`等函数。

感兴趣的话可以参考一下我的书，机工社《C++20高级编程》
<img width="771" alt="image" src="https://user-images.githubusercontent.com/11377070/185163758-61d73541-ed36-4341-a5cf-f42814a73ec5.png">

**Comment by BestUO** [comment]
> 以`co_await task`为例，由于`Task`类的`Promise`定义了`await_transform`函数，因此会调用
> 
> ```
> auto task_awaiter = p. await_transform(task);
> ```
> 
> 因为我的`await_transform`只是简单地透传一下`task`，所以
> 
> ```
> auto task_awaiter = task;
> ```
> 
> 接下来就是调用`task`对象的`operator co_await`操作符拿到真正的`awaiter`，编译器会展开`awaiter`里的`await_ready/await_suspend/await_resume`等函数。
> 


await_transform仅是透传，concepts::Awaitable的require要求重载co_await，明白了谢谢指教，另书已买还没到

**Comment by BestUO** [comment]
> 以`co_await task`为例，由于`Task`类的`Promise`定义了`await_transform`函数，因此会调用
> 
> ```
> auto task_awaiter = p. await_transform(task);
> ```
> 
> 因为我的`await_transform`只是简单地透传一下`task`，所以
> 
> ```
> auto task_awaiter = task;
> ```
> 
> 接下来就是调用`task`对象的`operator co_await`操作符拿到真正的`awaiter`，编译器会展开`awaiter`里的`await_ready/await_suspend/await_resume`等函数。
> 
> 感兴趣的话可以参考一下我的书，机工社《C++20高级编程》： <img alt="image" width="771" src="https://user-images.githubusercontent.com/11377070/185163758-61d73541-ed36-4341-a5cf-f42814a73ec5.png">
