### ISSUE TITLE
Just a comparison

### ISSUE THREAD

**Issue by beef9999** [netcan/asyncio#9]
https://github.com/alibaba/PhotonLibOS

First of all, Go and Rust should be faster than you thought. Wondering how you get such results.

Did you test it with two real machines?

**Comment by beef9999** [comment]
loopback device is not trustworthy for networking tests

**Comment by netcan** [comment]
> loopback device is not trustworthy for networking tests

just to test coroutine performance.(most tests are coroutine-based)
